sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    # cache node modules
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
    - examples/hello-world/client/node_modules

notifications:
  # disable email notification
  email: false

before_install:
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add coveralls
  # remove unused node modules from cache
  - npm prune
  - (cd examples/hello-world/client && npm prune)

install:
  - yarn
  - (cd examples/hello-world/client && rm -rf node_modules/angular2-apollo && npm i)

script:
  - yarn test
  # - (cd examples/hello-world/client && npm test)

after_script:
  # send code-coverage report to coveralls
  - coveralls < ./coverage/lcov.info || true
