sudo: false

language: node_js

node_js:
  - "0.12"
  - "2"
  - "4"
  - "5"

cache:
  directories:
    # cache node modules
    - node_modules

notifications:
  # disable email notification
  email: false

install:
  # use firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i
  - npm install -g typings
  - npm install -g coveralls
  # temporary fix
  - (cd node_modules/apollo-client && npm run compile)

script:
  # remove unused node modules from cache
  - npm prune
  # install typings
  - typings i
  # karma tests
  - npm test

after_script:
  # send code-coverage report to coveralls
  # - coveralls < ./coverage/lcov.info || true
