sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    # cache node modules
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

notifications:
  # disable email notification
  email: false

before_install:
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add coveralls
  # remove unused node modules from cache
  - npm prune

install: yarn

script: yarn test

after_script:
  # send code-coverage report to coveralls
  - coveralls < ./coverage/lcov.info || true
