blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/kamilkisiela/apollo-angular/discussions/new
    about: Request and discuss a feature
  - name: Ask a Question
    url: https://github.com/kamilkisiela/apollo-angular/discussions/new
    about: Ask questions and discuss with other community members
